### ISSUE TITLE
organization is not explained on main README

### ISSUE THREAD

**Issue by tdhock** [DorisAmoakohene/PerformanceTest_data.table#3]
@DorisAmoakohene on the main README in this repo, I was expecting to see something along the lines of "this repo is organized into folders, where Working Examples contains performance tests that are ready to use, other folder contains etc" can you please add this info at the top of the README, with a brief explanation of the goal/purpose of the repo?

**Comment by DorisAmoakohene** [comment]
This has been addressed. Thanks

**Comment by tdhock** [comment]
great
