### ISSUE TITLE
working examples not completely documented

### ISSUE THREAD

**Issue by tdhock** [DorisAmoakohene/PerformanceTest_data.table#4]
Hi @DorisAmoakohene I looked in Working Examples folder, and I was expecting comments on the same line of each commit ID, which document where the commit ID was taken from.
For example https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/master/Working%20Examples/PR%201534/shift%20in%20data.table%20v1.9.6%20is%20slow%20for%20many%20groups%20%231534%20-%20Copy.Rmd has the following with some comments, which are just links to some commits, which is not sufficient.
```r
  "Before"="4eada9760352d243896628ecaf61ec934338dc3b",#https://github.com/Rdatatable/data.table/commit/9e6e45301ea89227414a4f6df1ffc679c5c7ef1c
  "Regression"="9e6e45301ea89227414a4f6df1ffc679c5c7ef1c", #https://github.com/Rdatatable/data.table/commit/cd818080606591ac5348005732db0cadfb4e597c
  "Fixed"="e88826e94127991754a8821ac8149d15f1f9c3c2")#https://github.com/Rdatatable/data.table/commit/e88826e94127991754a8821ac8149d15f1f9c3c2
```
Can you please add comments to explain where each commit ID came from?
For example the following from https://github.com/DorisAmoakohene/PerformanceTest_data.table/commit/177279e12f502380d25d2ff8d3cb9dd4f19ec9da is good/sufficient, because it explains where we can find the commit IDs, in relation to the PRs/issues.
```r
"Before"="19b7866112614db53eb3e909c097407d91cd6738",#parent of the regression commit (https://github.com/Rdatatable/data.table/commit/0895fa247afcf6b38044bd5f56c0d209691ddb31), which is the parent of the first commit in the PR that causes the issue (https://github.com/Rdatatable/data.table/pull/5493/commits) 
  "Regression"="0895fa247afcf6b38044bd5f56c0d209691ddb31", #The regression commit is parent of the first commit in the PR that fixes the issue  (https://github.com/Rdatatable/data.table/pull/5493/commits)
  "Fixed"="1e03fe7b890e63da9651d997ea52548c90b3ae32")# last commit of the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/5493/commits)
```

**Comment by DorisAmoakohene** [comment]
Yes i have done that now @tdhock

**Comment by tdhock** [comment]
this is under Working examples, but still is not completely documented, https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/master/Working%20Examples/PR%204488/Selecting%20from%20data.table%20by%20row%20is%20very%20slow%20%233735%20-%20Copy.Rmd
can you please do that for all of the Working examples?
